services:
  api-demo:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: default
      DB_USER: postgres
      DB_PASSWORD: postgres
      REDIS_HOST: keydb
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - keydb

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: default
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8001:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  keydb:
    image: eqalpha/keydb:x86_64_v5.3.3
    container_name: keydb
    ports:
      - "6379:6379"
    restart: always
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  pgdata: